version: "3.8"
services:
  adminer:
    container_name: diploma-project-adminer
    image: adminer:4.8.1
    restart: always
  postgres:
    container_name: diploma-project-postgres
    image: postgres:15
    env_file:
      - apps/postgres/.docker/prod/.env
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    restart: always
  api:
    container_name: diploma-project-api
    build:
      context: apps/api
      dockerfile: .docker/prod/Dockerfile
    env_file:
      - apps/api/.docker/prod/.env
    restart: always
    depends_on:
      - postgres
  web:
    container_name: diploma-project-web
    build:
      context: apps/web
      dockerfile: .docker/prod_local/Dockerfile
    volumes:
      - ./storage/app/public/uploads:/app/uploads
    restart: always
    ports:
      - 8001:80
    depends_on:
      - api
      - adminer
